### ISSUE TITLE
Dynamic game objects are spawned incorrectly when changing regions?

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#136]
How its produced

http://recordit.co/dCymzeLUYs

**Comment by Major-** [comment]
Is this using master with no edits, or your own local fork? I was aware of this issue a while back, but was under the impression it was fixed.

**Comment by WizardJesse1** [comment]
@Major- every bug i report is tested on master with no edits

**Comment by Major-** [comment]
Okay, thanks

**Comment by ryleykimmel** [comment]
Well that stinks.

**Comment by Major-** [comment]
Looks like the items aren't being sent properly when the player teleports (i.e. loads an entirely new set of regions), as the same behaviour doesn't occur when walking between regions

**Comment by Major-** [comment]
Probably p-hard. You interested @ryleykimmel?

**Comment by ryleykimmel** [comment]
I'll take a look @Major-

**Comment by ryleykimmel** [comment]
```java
		Set<RegionCoordinates> differences = new HashSet<>(newViewable);
		differences.retainAll(oldViewable);

		Set<RegionCoordinates> full = new HashSet<>(newViewable);
		full.removeAll(oldViewable);
```

@Major- is this supposed to be like this?

**Comment by Major-** [comment]
Yes, although based just on that code snippet it is slightly confusing. `differences` is the `Set` of `RegionCoordinates` of regions that have had some form of region update occur in them, *and* were previously in view of the player (so we only need to send the updates to the player, not the entire region). 

`full` is the `Set` of `RegionCoordinates` of regions that *were not* in view of the player before, and so we have to send everything in that region, because the player has no previous information about it.
