### ISSUE TITLE
Many code duplication between r317 and r377

### ISSUE THREAD

**Issue by AymericDu** [apollo-rsps/apollo#294]
Hello,

There is a lot of code duplication between `r317` and `r377` in `game/src/main/org/apollo/game/release/`.

For example, some identical classes:
- `AddFriendMessageDecoder`
- `AddIgnoreMessageDecoder`
- `ArrowKeyMessageDecoder`
- `ButtonMessageDecoder`
- `ClearRegionMessageEncoder`
- ...

I think it would be nice to make a big refactor.

What do you think ?

If you agree, I can do it.

**Comment by Major-** [comment]
Yeah the plan for this is to generate these classes at runtime (there's a codec_generation branch @garyttierney and I are working on sporadically), so eventually almost all of the `BlahDecoder` and `BlahEncoder` classes will be gone.

For now I think it's easier if we just leave them as-is, with the duplicate code - otherwise we're just putting effort into code that's going to all be deleted soon anyway.

I'll leave this issue open as a reminder for tracking the codec_gen stuff, thanks for opening it.

**Comment by AymericDu** [comment]
Okay ! Thanks for the explanation.
