### ISSUE TITLE
[dialogues] NPC head animations

### ISSUE THREAD

**Issue by Tim-W** [apollo-rsps/apollo#65]
NPC head animations do not work on both 377 and 317. When using the dialogue plugin, only a static image of the NPC head is shown.

Should this be fixed plugin-wise or in core?

**Comment by Major-** [comment]
Can you provide the code you are using?

**Comment by Tim-W** [comment]
I've not written any dialogue code, I've just used the built in tutorial island plugin together with the dialogue plugin to test tutorial island. The npc head of the runescape guide wasn't moving in the  dialogue.

**Comment by WizardJesse1** [comment]
there is a packet which apollo does not have for interface animations

**Comment by Tim-W** [comment]
@WizardJesse1 So... perhaps we should implement the packet? 

What's the opcode?

**Comment by WizardJesse1** [comment]
200 - Animate component (not sure)
interfaceId - Short
animationId - Short

**Comment by Tim-W** [comment]
Shouldn't be hard to implement. Would you accept pull requests to implement this @Major- ?

**Comment by lare96** [comment]
im sure he wouldn't object to a pull req

**Comment by Major-** [comment]
Apollo does have this frame @WizardJesse1 @Tim-W, it's called [SetWidgetModelAnimation](https://github.com/apollo-rsps/apollo/blob/master/game/src/main/org/apollo/game/message/impl/SetWidgetModelAnimationMessage.java).

The actual issue is that the [emote is never set](https://github.com/apollo-rsps/apollo/blob/master/data/plugins/location/tutorial-island/guide.rb#L36) in any of the dialogues, and that the frame is not sent when the dialogue is. The dialogue code is all cobbled together and needs rewriting in an actual OO manner at some point, so this probably isn't the only issue with them.

**Comment by ryleykimmel** [comment]
I implemented this today, care for a PR?

http://recordit.co/bsMIFshRme
